---
- template: src=mailname.j2 dest=/etc/mailname mode=0644

- copy: src=rcS dest=/etc/default/rcS mode=0644 owner=root group=root

- file: path=/etc/apt/apt.conf state=touch owner=root group=root mode=0644

- name: install base packages for the system
  apt: pkg={{ item }} state=present update_cache=yes
  with_items:
    - apt-transport-https
    - dbus
    - ethtool
    - fail2ban
    - git
    - htop
    - ifenslave-2.6
    - libsasl2-modules
    - lldpd
    - lsof
    - make
    - mercurial
    - mercurial-common
    - monit
    - moreutils
    - ntp
    - postfix
    - python-pycurl
    - python-software-properties
    - tshark
    - unattended-upgrades 
    - unzip
  tags:
    - install

# Remove unused kernels
- apt: pkg={{ item }} state=absent
  with_items:
    - sensible-mda
    - sendmail
    - sendmail-base
    - sendmail-cf

- template: src=monitrc.j2 dest=/etc/monit/monitrc
  notify: reload monit configuration

- name: Ensure monit is running
  service: name=monit state=started enabled=yes

- name: Ensure ntp is running
  service: name=ntp state=started
