---
- include: mounts.yml
- include: apt.yml
- include: basepackages.yml
- include: ssh.yml
- include: host.yml
- include: security.yml
- include: timezone.yml
- include: postfix.yml
- include: logrotate.yml
