---
- include: mounts.yml
  when: mount_disks|default(false)
  tags: mounts
- include: apt.yml
- include: basepackages.yml
- include: ssh.yml
  tags: ssh_keys
- include: host.yml
- include: security.yml
- include: timezone.yml
- include: logrotate.yml
