---
- name: SSH folder voor root
  file: path="/root/.ssh" state=directory

- name: SSH Authorized_keys voor root
  copy: src=authorized_keys dest=/root/.ssh/authorized_keys

- copy: src=sshd_config dest=/etc/ssh/sshd_config
  notify:
  - restart ssh

- group: name=admin system=yes
  tags: user

- name: Create group for main user
  group:
    name: "{{ ubuntu_user }}"

- name: Create main user
  user:
    name: "{{ ubuntu_user }}"
    shell: "/bin/bash"
    group: admin
    groups: "{{ ubuntu_user }}"
    append: yes
    password: "{{ encrypted_ssh_password }}"
    update_password: always
    generate_ssh_key: yes
    ssh_key_type: rsa
    ssh_key_file: "/home/{{ ubuntu_user }}/.ssh/id_rsa"
  tags: user

# - user: name=wijnand comment="Wijnand" uid=1109 password={{ encrypted_ssh_password }} shell="/bin/bash" state=present group=wijnand groups=admin append=yes generate_ssh_key=yes ssh_key_file="/home/wijnand/.ssh/id_rsa" ssh_key_type=rsa update_password=always
#   tags: user

- name: set sudoers file
  copy: src=sudoers dest=/etc/sudoers
  tags: sudo

- name: SSH folder voor {{ ubuntu_user }}
  file: path="/home/{{ ubuntu_user }}/.ssh" state=directory group="{{ ubuntu_user }}" owner="{{ ubuntu_user }}" mode="0700"

- name: SSH Authorized_keys voor {{ ubuntu_user }}
  copy: src=authorized_keys dest="/home/{{ ubuntu_user }}/.ssh/authorized_keys"  group="{{ ubuntu_user }}" owner="{{ ubuntu_user }}" mode="0600"

- name: Enable SSHD
  service: name=ssh enabled=yes
