---
- name: SSH folder voor root
  file: path="/root/.ssh" state=directory

- name: SSH Authorized_keys voor root
  copy: src=authorized_keys dest=/root/.ssh/authorized_keys

- copy: src=sshd_config dest=/etc/ssh/sshd_config
  notify:
  - restart ssh
  tags: blaat

- copy: src=sudoers dest=/etc/sudoers
  tags: sudo

- group: name=admin system=yes

- user: name=wijnand comment="Wijnand" uid=1109 password={{ encrypted_ssh_password }} shell="/bin/bash" state=present group=admin append=yes generate_ssh_key=yes ssh_key_file="/home/wijnand/.ssh/id_rsa" ssh_key_type=rsa update_password=always

- group: name=wijnand state=present

- name: SSH folder voor wijnand
  file: path="/home/wijnand/.ssh" state=directory group="wijnand" owner="wijnand" mode="0700"

- name: SSH Authorized_keys voor wijnand
  copy: src=authorized_keys dest=/home/wijnand/.ssh/authorized_keys  group="wijnand" owner="wijnand" mode="0600"

- name: Enable SSHD
  service: name=ssh enabled=yes
