---
- name: set /etc/localtime to Europe/Amsterdam
  file: src=/usr/share/zoneinfo/Europe/Amsterdam dest=/etc/localtime state=link force=yes

- name: set /etc/timezone to Europe/Amsterdam
  copy:
   content: |
     Europe/Amsterdam
   dest: /etc/timezone
  notify: update tzdata
