---
- hosts: htpc
  become: yes
  become_method: sudo
  vars_files: ["{{ vars_file }}"]
  roles:
    - { role: baserole, tags: baserole }
    - { role: ufw, tags: ufw }
    - { role: encfs, tags: encfs }
    - { role: logrotate, tags: logrotate }
    - { role: syncthing, syncthing_use_systemd: false, syncthing_use_supervisor: true, tags: syncthing }
    - { role: datadog, tags: datadog }
    - { role: vnc, tags: vnc }
    - { role: greyhole, tags: greyhole }
    - { role: docker, docker-py: yes, tags: docker }
    - { role: prometheus, prometheus_components: ["prometheus", "alertmanager"], prometheus_alertmanager_url: "http://localhost:9093/", tags: prometheus }
    - { role: sabnzbd, tags: sabnzbd }
    - { role: sonarr, tags: sonarr }
    - { role: rclone, tags: rclone }
    - { role: plexmediaserver, install_plex: true, install_plexwatch: true, use_acd: yes, tags: plexmediaserver }
    - { role: kodi, tags: kodi }

- hosts: toaster
  become: yes
  become_method: sudo
  vars_files: ["{{ vars_file }}"]
  roles:
    - { role: baserole, tags: baserole }
    - { role: logrotate, tags: logrotate }
    - { role: rclone, tags: rclone }
    - { role: rclone, tags: rclone }
    - { role: plexmediaserver, install_plex: true, install_plexwatch: true, use_acd: yes, tags: plexmediaserver }
    - { role: syncthing, tags: syncthing }
