---

- hosts: all
  sudo: yes
  vars_files: ["{{ vars_file }}"]
  roles:
    - { role: baserole, tags: baserole }

- hosts: htpc
  sudo: yes
  vars_files: ["{{ vars_file }}"]
  roles:
    - { role: baserole, tags: baserole }
    - { role: ufw, tags: ufw }
