---
# mkdir .acd # encrypted dir for mounted amazond cloud drive
# mkdir acd # decrypted dir for ACD
# mkdir .local_acd # encrypted dir for uploading to ACD
# mkdir local_acd # decrypted dir for uploading to ACD
# mkdir media # Fusion dir that shows both local_acd and mounted acd files. Point Plex to this dir

- name: unmount encfs directories
  shell: |
    /bin/fusermount -uz /home/{{ plex.user }}/acd
    /bin/fusermount -uz /home/{{ plex.user }}/.acd
    /bin/fusermount -uz /home/{{ plex.user }}/local_acd
    /bin/fusermount -uz /home/{{ plex.user }}/.local_acd
    /bin/fusermount -uz /home/{{ plex.user }}/media
  failed_when: false

- name: Create enfs directories
  file:
    path: "/home/{{ plex.user }}/{{ item }}"
    owner: "{{ plex.user }}"
    group: "{{ plex.group }}"
    state: directory
  with_items:
    - .acd
    - acd
    - .local_acd
    - local_acd
    - media
    - script

- name: Copy encfs mount script
  template:
    src: encfs_mount_acd.sh.j2
    dest: "/home/{{ plex.user }}/script/encfs_mount_acd.sh"
    owner: "{{ plex.user }}"
    group: "{{ plex.group }}"
    mode: 0700

- name: Create cron to mount ACD
  cron:
    name: "Mount encfs and rclone directories"
    user: "{{ plex.user }}"
    minute: "*"
    hour: "*"
    job: "/home/{{ plex.user }}/script/encfs_mount_acd.sh check"

- name: Copy 'rclone copy to acd' script
  template:
    src: rclone_copy_acd.sh.j2
    dest: "/home/{{ plex.user }}/script/rclone_copy_acd.sh"
    owner: "{{ plex.user }}"
    group: "{{ plex.group }}"
    mode: 0700

- name: Create encfs logging directories
  file:
    path: "/var/log/rclone"
    owner: "{{ plex.user }}"
    group: "{{ plex.group }}"
    state: directory

- cron:
    name: SHELL
    env: yes
    value: /bin/bash

- name: Create cron to ron rclone copy to acd
  cron:
    name: "rclone move (upload) to acd"
    user: "{{ plex.user }}"
    minute: "0"
    hour: "*"
    job: "flock -n /tmp/rclone.lock -c /home/{{ plex.user }}/script/rclone_copy_acd.sh"

- name: Place encfs.xml file
  template:
    src: encfs_acd.xml.j2
    dest: "/home/{{ plex.user }}/encfs_acd.xml"
    owner: "{{ plex.user }}"
    group: "{{ plex.group }}"
    mode: 0400

- name: Place encfs password file
  template:
    src: encfs_acd_pass.j2
    dest: "/home/{{ plex.user }}/encfs_acd_pass"
    owner: "{{ plex.user }}"
    group: "{{ plex.group }}"
    mode: 0400
  no_log: true

- name: Install Union-FS
  apt:
    name: unionfs-fuse
    state: present

- name: Allow others to read and write to unionfs directory
  lineinfile:
    dest: /etc/fuse.conf
    state: present
    regexp: '^#user_allow_other\s'
    line: 'user_allow_other'

- name: Create fuse group
  group:
    name: "fuse"
    system: yes

- name: Add the user to fuse group
  user:
    name: "{{ plex.user }}"
    groups: fuse
    append: yes
