---
- name: Create plex group
  group:
    name: "{{ plex.group }}"
    system: yes

- name: Create plex user
  user:
    name: "{{ plex.user }}"
    home: "/home/{{ plex.user }}"
    group: "{{ plex.group }}"
    system: yes

- name: Add plexmediaserver ppa
  apt_repository:
    repo: "deb https://downloads.plex.tv/repo/deb/ public main"
    state: present
    filename: plexmediaserver


- name: Add plexmediaserver ppa key
  apt_key:
    url: "https://downloads.plex.tv/plex-keys/PlexSign.key"
    state: present

- name: Install plexmediaserver
  apt:
    name: plexmediaserver
    update_cache: yes
    state: present

- name: Copy default config to /etc/default/plexmediaserver
  template:
    src: plex_default.j2
    dest: "/etc/default/plexmediaserver"
    owner: root
    group: root
    mode: 0644
  become: yes
  become_method: sudo
  notify: restart plex

- name: Create plex systemctl service
  template:
    src: plex_service.j2
    dest: /etc/systemd/system/plexmediaserver.service
    owner: root
    group: root
    mode: 664
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Enable plexmediaserver service at startup (16.04)
  systemd:
    name: plexmediaserver
    enabled: yes
    daemon_reload: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '16.04'

- name: Enable plexmediaserver service at startup (14.04)
  service:
    name: plexmediaserver
    enabled: yes
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version == '14.04'

- name: Ufw open tcp ports
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - 32400 #(for access to the Plex Media Server) [required]
    - 32469 #(for access to the Plex DLNA Server)
    - 61636
  tags: ufw

- name: Ufw open udp ports
  ufw: rule=allow port={{ item }} proto=udp
  with_items:
    - 1900 #(for access to the Plex DLNA Server)
    - 32410 #(for current GDM network discovery)
    - 32412 #(for current GDM network discovery)
    - 32413 #(for current GDM network discovery)
    - 32414 #(for current GDM network discovery)
    - 65535
  tags: ufw

- include: acd.yml
  when: use_acd
  tags: plex_acd

- include: plexwatch.yml
  when: install_plexwatch
  tags: plexwatch
