---
# Dependencies
- name: Ensure plex dependencies are installed
  action: apt pkg={{ item }} state=present
  register: result
  with_items:
    - libavahi-common3
    - libavahi-core7
    - libdaemon0
    - libnss-mdns
    - libavahi-client3
    - libavahi-common3
    - avahi-daemon
    - avahi-utils
  ignore_errors: yes
- name: Running apt-get -f install to fix any potential problems the last command had
  command: apt-get -f install
  when: result|failed

# Install
- name: Download plex .deb
  get_url: url={{ plex_download }} dest={{ plex_deb_path }}
  ignore_errors: yes
- name: Check if plex is installed
  command: "dpkg -s plexmediaserver"
  register: result
  changed_when: False
  ignore_errors: yes
- name: Installing plex
  command: "dpkg -i {{ plex_deb_path }}"
  when: result|failed

- name: Copy default config to /etc/default/plexmediaserver
  template: src=plex_default.j2 dest="/etc/default/plexmediaserver" owner=root group=root mode="0644"
  become: yes
  become_method: sudo
  notify: restart plex

- name: Copy plex config to /var/lib/plexmediaserver/Library/Application\ Support/Plex\ Media\ Server/
  template: src=plexconfig.j2 dest="/home/wijnand/Library/Application Support/Plex Media Server/Preferences.xml" owner=plex group=plex mode="0644"
  notify: restart plex

# Start it
- name: Ensure plex is running
  service: name=plexmediaserver state=started

- name: Ufw open plex port
  ufw: rule=allow port={{ sonarr_port_external }} proto=tcp 

- name: Ufw open tcp ports
  ufw: rule=allow port={{ item }} proto=tcp 
  with_items:
    - 32400
    - 32469
    - 61636

- name: Ufw open udp ports
  ufw: rule=allow port={{ item }} proto=udp 
  with_items:
    - 32413
    - 1900
    - 32412
    - 32410
    - 32414
    - 65535

