---
- name: Create plexpy config/database dir
  file:
    path: /home/{{ plex.user }}/plexpy
    state: directory
    owner: "{{ plex.user }}"
    group: "{{ plex.user }}"
    mode: 0700

- name: Fetch user id
  shell: "id -u {{ plex.user }}"
  register: fetched_user_id

- name: Fetch user group id
  shell: "id -g {{ plex.user }}"
  register: fetched_group_id

# env PUID and PGID should use same user id
# and group id as the user that mounted any data (media) volumes
- name: start plexwatch container
  become: yes
  become_user: "{{ plex.user }}"
  docker:
    name: plexpy
    image: "linuxserver/plexpy"
    state: reloaded
    pull: missing
    restart_policy: always
    ports:
    - "{{ plexpy.ports }}{{ ':' }}8181"
    env:
      PUID: "{{ fetched_user_id.stdout }}"
      PGID: "{{ fetched_group_id.stdout }}"
    volumes:
    - "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server/Logs{{ ':' }}/logs{{ ':' }}ro"
    - "/home/{{ plex.user }}/plexpy/{{ ':' }}/config"
