---
- name: Install the GUI and VNC Packages
  apt: pkg={{ item }} state=installed update_cache=true
  with_items:
    - x11vnc

- shell: "sudo x11vnc -storepasswd {{ vnc_password }} /etc/x11vnc.pass"

- template: src=x11vnc.conf.j2 dest=/etc/init/x11vnc.conf

- name: Ufw open tcp ports
  ufw: rule=allow port=5900 proto=tcp 
