---

- name: Create sonarr config dir
  file: path=/home/wijnand/docker/dockerspace/sonarr/sonarr/ state=directory owner=nobody group=nogroup

- name: Copy sonarr config
  template: src=config.xml.j2 dest=/home/wijnand/docker/dockerspace/sonarr/sonarr/config.xml owner=nobody group=nogroup

- name: start sonarr container
  sudo: no
  docker:
    name: sonarr
    image: "{{ hub_username }}/{{ sonarr_hub_repository }}"
    state: reloaded
    pull: missing
    restart_policy: always
    ports:
    - "{{ sonarr_ports }}"
    volumes:
    - "{{ mnt_series }}{{ ':' }}/volumes/media"
    - "{{ sonarr_datadir }}{{ ':' }}/volumes/config"
    - "{{ sab_downloaddir }}{{ ':' }}/volumes/completed"
    links:
    - "{{ sab_containername }}{{ ':' }}sabnzbd"


- name: Ufw open sonarr port
  ufw: rule=allow port={{ sonarr_port_external }} proto=tcp 

