---
- name: Mount drives
  file: path={{ mount_path }}/{{ item }} state=directory
    owner=root group=root
  with_items: "{{ storage_pool_drives }}"

- apt_repository: repo='deb http://www.greyhole.net/releases/deb stable main' state=present
- apt_key: url=http://www.greyhole.net/releases/deb/greyhole-debsig.asc state=present

- name: Install common packages
  apt: name={{ item }} state=installed update_cache=yes
  with_items:
    - samba
    - greyhole
    - system-config-samba
    - cifs-utils
    - curl
    - python-mysqldb
    - python-apt

- name: Start MySQL service
  service: name=mysql state=started enabled=yes

- name: Create MySQL db
  mysql_db: name={{ db_name }} state=present

- name: Create MySQL user
  mysql_user: name={{ db_user }} password={{ db_pass }} state=present
    priv=greyhole.*:ALL

- name: Import MySQL db
  mysql_db: name={{ db_name }} login_user={{ db_user }} login_password={{ db_pass }}
    state=import target=/usr/share/greyhole/schema-mysql.sql
  ignore_errors: yes

- name: Copy greyhole.conf
  template: src=greyhole.conf.j2 dest=/etc/greyhole.conf
    owner=root group=root mode=0644

- copy: src=greyhole.monit dest=/etc/monit/conf.d/greyhole.conf
  notify: reload monit configuration

- name: Copy samba config to /etc/samba/smb.conf
  template: src=smb.conf.j2 dest=/etc/samba/smb.conf owner=root group=root mode="0644"
  notify: restart samba

- name: Copy samba automount script
  template: src=samba_automount.j2 dest=/etc/init.d/mount_shares_locally mode="0755"
  become: yes
  become_method: sudo
  tags: greyholemount

- name: update-rc.d with automount
  become: yes
  become_method: sudo
  shell: update-rc.d mount_shares_locally defaults

- shell: if [ -f /sbin/chkconfig ]; then sudo chkconfig --add mount_shares_locally; fi

- name: Copy samba credentials to /home/wijnand/.smb_credentials
  template: src=samba_credentials.j2 dest=/home/wijnand/.smb_credentials owner=wijnand group=wijnand

- shell: /etc/init.d/mount_shares_locally start
  become: yes
  become_method: sudo

#Hey! if samba won't accept your credentials thats because you probably don't have that user in samba.
#Create a new user and password using: "sudo smbpasswd -a [username]" and it will prompt you for a password.
