---

- name: Create sabnzbd config dir
  file: path={{ sab_datadir }}/ state=directory owner=wijnand group=wijnand

- name: Copy sabnzbd config file
  template: src=sabnzbd.ini.j2 dest={{ sab_datadir }}/sabnzbd.ini

- name: start sabnzbd container
  sudo: no
  tags: sabnzbd
  docker: 
    name: sabnzbd
    privileged: yes
    image: "{{ hub_username }}/{{ sab_hub_repository }}"
    state: reloaded
    pull: missing
    restart_policy: always
    ports:
    - "{{ sab_ports }}"
    volumes:
    - "{{ sab_downloaddir }}{{ ':' }}/data/downloads"
    - "{{ sab_datadir }}{{ ':' }}/data/sabnzbd"
    - "{{ sab_nzbbackupdir }}{{ ':' }}/data/nzb"

- name: Ufw open sabnzbnd port
  ufw: rule=allow port={{ sonarr_port_external }} proto=tcp 

- name: Ufw open tcp ports
  ufw: rule=allow port={{ item }} proto=tcp 
  with_items:
    - 8080 #Sabnzbd

    # j# Allow incoming TCP ports
    # jTCP_IN = "
    #- 56874
    # j- 20
    # j- 21
    # j- 22
    # j- 25
    # j- 53
    # j- 80
    # j- 110
    # j- 143
    # j- 443
    # j- 465
    # j- 587
    # j- 993
    # j- 995
    # j- 2077
    # j- 2078
    # j- 2082
    # j- 2083
    # j- 2086
    # j- 2087
    # j- 2095
    # j- 2096
    # j- 5900
    # j- 56874
    # j- 32400
    # j- 32469
    # j- 61636
    # j- 8080
    # j- 9090
    # j- 65535
    # j- 7999
    # j- 7777
    # j- 3000"
    # j
    # j# Allow outgoing TCP ports
    # jTCP_OUT = "20,21,22,25,37,43,53,80,110,113,443,587,873,993,995,2086,2087,2089,2703,1900,119,8080,9777,3000,9418"
    # j
    # j# Allow incoming UDP ports
    # jUDP_IN = "20,21,53,32400,32410,32412,32414,1900,35689,50605,5353,1900,32469,17500,15963,57621,45980,43595,5632,54623,3502,8080,9777,55718,39665,36635,3000"
    # j
    # j# Allow outgoing UDP ports
    # j# To allow outgoing traceroute add 33434:33523 to this list
    # jUDP_OUT = "20,21,53,113,123,873,6277,32400,17500,57621,32414,32412,1900,68,67,8080,9777,5353,3000"
