---

- name: Create sabnzbd config dir
  file: path={{ sab_datadir }}/ state=directory owner=wijnand group=wijnand

- name: Copy sabnzbd config file
  template: src=sabnzbd.ini.j2 dest={{ sab_datadir }}/sabnzbd.ini

- name: start sabnzbd container
  become: yes
  become_user: "{{ ubuntu_user }}"
  tags: sabnzbd
  docker:
    name: sabnzbd
    privileged: yes
    image: "{{ hub_username }}/{{ sab_hub_repository }}"
    state: reloaded
    pull: missing
    restart_policy: always
    ports:
    - "{{ sab_ports }}"
    volumes:
    - "{{ sab_downloaddir }}{{ ':' }}/data/downloads"
    - "{{ sab_datadir }}{{ ':' }}/data/sabnzbd"
    - "{{ sab_nzbbackupdir }}{{ ':' }}/data/nzb"

- name: Ufw open sabnzbnd port
  ufw: rule=allow port={{ sonarr_port_external }} proto=tcp

- name: Ufw open tcp ports
  ufw: rule=allow port={{ item }} proto=tcp
  with_items:
    - 8080
