---
- name: docker repo requires https transport
  apt: pkg=apt-transport-https state=present update_cache=no

- name: install apt-key docker
  apt_key: keyserver="p80.pool.sks-keyservers.net" id="58118E89F3A912897C070ADBF76221572C52609D"

- apt_repository: repo="deb https://get.docker.com/ubuntu docker main" state=absent
- apt_repository: repo="deb https://apt.dockerproject.org/repo ubuntu-trusty main" state=present

- apt: pkg=lxc-docker state=absent purge=yes

- apt: pkg={{item}} state=present update_cache=yes
  with_items:
   - docker-engine
   - apparmor

- user: name=wijnand groups=docker append=yes

- service: name=docker state=started

- include: docker-py.yml
  when: docker-py

- name: Create /home/wijnand/.docker directory
  file: path=/home/wijnand/.docker state=directory

- template: src=dockercfg.j2 dest=/home/wijnand/.docker/config.json mode=600 owner=wijnand group=wijnand

- name: Add {{ ubuntu_user }} and datadog to docker group
  user: name={{ item }} group=docker createhome=no state=present
  with_items:
    - "{{ ubuntu_user }}"
    - "dd-agent"
  tags: datadog

- template: src=docker.datadog dest=/etc/dd-agent/conf.d/docker_daemon.yaml owner=dd-agent mode=0644
  notify: restart datadog
  tags: datadog

- name: start cAdvisor container
  become: yes
  become_method: sudo
  docker:
    name: cAdvisor
    privileged: yes
    image: "google/cadvisor:latest"
    state: reloaded
    pull: missing
    restart_policy: always
    ports:
    - "8030:8080"
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:rw"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
