---
vars_file: prod_variables.yml
htpc_environment: production

ubuntu_user: wijnand

# General docker
mnt_series: /mnt/samba/Series

# Sabnzbd
sab_containername: sabnzbd
sab_imagename: latest
sab_hub_repository: sabnzbd
sab_ports: "{{ sab_port_external }}{{ ':' }}{{ sab_port_internal }}"
sab_port_internal: 8080
sab_port_external: 8080

sab_downloaddir: /mnt/hdd1/sabnzbd
sab_datadir: /home/wijnand/docker/dockerspace/sabnzbd
sab_nzbbackupdir: /home/wijnand/Downloads/sabnzbd/nzb

# Sonarr
sonarr_containername: sonarr
sonarr_imagename: latest
sonarr_hub_repository: sonarr
sonarr_ports: "{{ sonarr_port_external }}{{ ':' }}{{ sonarr_port_internal }}"
sonarr_destdir: /mnt/samba/Series
sonarr_datadir: /home/wijnand/docker/dockerspace/sonarr
sonarr_port_internal: 8989
sonarr_port_external: 8989

# Plexmediaserver
plex_download: "https://plex.tv/downloads/latest/1?channel=16&build=linux-ubuntu-x86_64&distro=ubuntu&X-Plex-Token={{ plex_token }}"
plex_deb_path: /tmp/plexmediaserver.deb
plex_application_support_dir: "/var/lib/plexmediaserver/Library/Application Support/Plex Media Server"

# Kodi

# Package/System configuration
kodi_conf_dir: "/home/{{ ubuntu_user}}/.kodi"
kodi_pkg_apt_repo: ppa:team-xbmc/ppa
kodi_pkg_apt_ver: "2:14.2"

# Arrays of filepaths. Reccomended to override.
kodi_source_files: []
kodi_source_music: []
kodi_source_pictures: []
kodi_source_programs: []
kodi_source_videos: [ '/mnt/samba/Movies/', '/mnt/samba/Series/' ]

# Optional settings (Not defined by default)
# kodi_advanced_settings:|
# kodi_mysql_server:
# kodi_mysql_user:
# kodi_mysql_pass:
# kodi_pkg_pvr:

# Prometheus
prometheus_version:                 1.0.0
prometheus_node_exporter_version:   0.12.0
prometheus_alertmanager_version:    0.3.0

# Syncthing
syncthing_version: 0.14.23
syncthing_url: https://github.com/syncthing/syncthing/releases/download/v{{syncthing_version}}/syncthing-{{ansible_system|lower}}-{{serf_architecture[ansible_architecture]}}-v{{syncthing_version}}.tar.gz
syncthing_user: syncthing
syncthing_address: 0.0.0.0:8090
syncthing_listen: 0.0.0.0:22000
syncthing_home: /home/syncthing
syncthing_localannounce: true
syncthing_globalannounce: true
syncthing_upnp: true


syncthing_use_ufw: true
syncthing_use_systemd: true
syncthing_use_supervisor: false
